# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "@xrdocs-images"
title_separator          : "-"
name                     : &name "Cisco Systems Inc"
description              : &description "repository to host images for xr-docs"
url                      : https://xrdocs.github.io/ # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : /xrdocs-images # the subpath of your site, e.g. "/blog"

host: "0.0.0.0"
port: 4000
